
var datos = angular.module("datos",[]);

datos.controller("controlador", function($scope){
	var random = function(){
		return 0.5 - Math.random();
	}

  $scope.info= angular.fromJson(window.sessionStorage.cuenta);
 

  $scope.examinar = function(cuenta){
    window.sessionStorage["cuenta"] = angular.toJson(cuenta);
	console.log(cuenta.Nombre);
	cuenta2 = cuenta;
  }

	
	var lista = this;
	lista.comedores = [
		
                        {
                          wkt_geom: "Point (-6538023.27961185202002525 -4656994.42139083333313465)",
                          url_img:"http://placehold.it/700x400",
                          id: "0",
                          Nombre: "COMEDOR DE LA FAMILIA",
                          Calle: "60",
                          Altura: "2035",
                          per_juridi: "NO",
                          Encargado: "Maria del Carmen Gongora",
                          aÑo_inicio: "2011",
                          origen_inf: "PROPIETARIOS",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "2",
                          ninos: "120",
                          adultos: "0",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "INSUFICIENTE",
                          Luz: "NO",
                          Gas: "NO",
                          Agua: "SI",
                          Cloacas: "NO",
                          Internet: "NO",
                          Telefonia: "SI",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "NO",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "NO",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "6",
                          Nro_volunt: "6",
                          Capacitac: "NO",
                          Hora_rotat: "SI",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "NO PERECEDEROS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "NO",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "NO",
                          MERIENDA: "SI",
                          ALMUERZO: "SI",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6541285.32927279733121395 -4656464.11664371844381094)",
                          url_img:"http://placehold.it/700x400",
                          id: "1",
                          Nombre: "PEQUEÑOS GIGANTES",
                          Calle: "96",
                          Altura: "3285",
                          per_juridi: "TRAMT",
                          Encargado: "JOSE EDUARDO ALLENDE",
                          aÑo_inicio: "2018",
                          origen_inf: "PROPIETARIOS",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "6",
                          ninos: "50",
                          adultos: "30",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "INSUFICIENTE",
                          Mobiliario: "INSUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "SI",
                          Limpieza: "SI",
                          Matafuegos: "NO",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "7",
                          Nro_volunt: "7",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "ALIMENTOS",
                          Origen_fon: "DONACION",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "SI",
                          Apoyo_esco: "TRAMT",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "SI",
                          MERIENDA: "SI",
                          ALMUERZO: "NO",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6540288.48305444698780775 -4656945.32337926141917706)",
                          url_img:"http://placehold.it/700x400",
                          id: "2",
                          Nombre: "CENTRO COMUNITARIO MATEO",
                          Calle: "82",
                          Altura: "3055",
                          per_juridi: "TRAMT",
                          Encargado: "ELISA MABEL ROLDAN",
                          aÑo_inicio: "1999",
                          origen_inf: "PROPIETARIOS",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "6",
                          ninos: "",
                          adultos: "",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "NO",
                          Telefonia: "SI",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "REGULAR",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "11",
                          Nro_volunt: "11",
                          Capacitac: "SI",
                          Hora_rotat: "SI",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "",
                          Ropa_calza: "",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "NO",
                          MERIENDA: "NO",
                          ALMUERZO: "NO",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6540992.20159608218818903 -4658962.3188211964443326)",
                          url_img:"http://placehold.it/700x400",
                          id: "3",
                          Nombre: "COMEDOR GENERAL SAN MARTIN",
                          Calle: "89",
                          Altura: "3536",
                          per_juridi: "NO",
                          Encargado: "SUSANA VOMERO",
                          aÑo_inicio: "1989",
                          origen_inf: "DONACION",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "5",
                          ninos: "92",
                          adultos: "92",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "SI",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "3",
                          Nro_volunt: "0",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "MUNICIPIO",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "SI",
                          Apoyo_esco: "NO",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "SI",
                          MERIENDA: "NO",
                          ALMUERZO: "NO",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6538968.83511688932776451 -4659841.89672944974154234)",
                          url_img:"http://placehold.it/700x400",
                          id: "4",
                          Nombre: "COMEDOR SUR",
                          Calle: "77",
                          Altura: "1865",
                          per_juridi: "NO",
                          Encargado: "ANALIA BARREIRA Y MARIANA VILLAJAÑE",
                          aÑo_inicio: "1992",
                          origen_inf: "COMODATO",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "5",
                          ninos: "40",
                          adultos: "21",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "2",
                          Nro_volunt: "0",
                          Capacitac: "SI",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "MUNICIPIO",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "SI",
                          Apoyo_esco: "NO",
                          Ropa_calza: "NO",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "NO",
                          MERIENDA: "SI",
                          ALMUERZO: "NO",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6538785.9488709419965744 -4658491.23683113232254982)",
                          url_img:"http://placehold.it/700x400",
                          id: "5",
                          Nombre: "PRECIOSA SEMILLA",
                          Calle: "54",
                          Altura: "3047",
                          per_juridi: "NO",
                          Encargado: "JULIANA BRAVO",
                          aÑo_inicio: "2008",
                          origen_inf: "ALQUILER",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "7",
                          ninos: "12",
                          adultos: "0",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "SI",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "12",
                          Nro_volunt: "0",
                          Capacitac: "SI",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "MUNICIPIO",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "SI",
                          MERIENDA: "SI",
                          ALMUERZO: "SI",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6541120.95285869389772415 -4658147.64748758170753717)",
                          url_img:"http://placehold.it/700x400",
                          id: "6",
                          Nombre: "LA CASITA PARA MERENDAR",
                          Calle: "81",
                          Altura: "3874",
                          per_juridi: "NO",
                          Encargado: "ALICIA DOVIGO",
                          aÑo_inicio: "2000",
                          origen_inf: "DONACION",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "5",
                          ninos: "35",
                          adultos: "0",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "INSUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "NO",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "NO",
                          Telefonia: "NO",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "3",
                          Nro_volunt: "0",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "AMBOS",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "NO",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "SI",
                          MERIENDA: "NO",
                          ALMUERZO: "SI",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6542164.2225993387401104 -4655859.43538546841591597)",
                          url_img:"http://placehold.it/700x400",
                          id: "7",
                          Nombre: "LOS MALVONES",
                          Calle: "69",
                          Altura: "",
                          per_juridi: "NO",
                          Encargado: "SUSANA",
                          aÑo_inicio: "",
                          origen_inf: "DONACION",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "7",
                          ninos: "32",
                          adultos: "0",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "NO",
                          Internet: "NO",
                          Telefonia: "NO",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "NO",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "NO",
                          Condicion: "REGULAR",
                          Mantenimie: "POCO",
                          Nro_trabaj: "10",
                          Nro_volunt: "10",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "NO",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "SI",
                          MERIENDA: "SI",
                          ALMUERZO: "SI",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6538240.94018657319247723 -4659750.13376642018556595)",
                          url_img:"http://placehold.it/700x400",
                          id: "8",
                          Nombre: "HOGAR EMANUEL",
                          Calle: "69",
                          Altura:"1546",
                          per_juridi: "NO",
                          Encargado: "MONICA",
                          aÑo_inicio: "1996",
                          origen_inf: "PRESTADO",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "7",
                          ninos: "3",
                          adultos: "6",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "INSUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "SI",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "1",
                          Nro_volunt: "1",
                          Capacitac: "SI",
                          Hora_rotat: "NO",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "SI",
                          Apoyo_esco: "NO",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "SI",
                          MERIENDA: "SI",
                          ALMUERZO: "SI",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6540386.20352294109761715 -4655750.94127716310322285)",
                          url_img:"http://placehold.it/700x400",
                          id: "9",
                          Nombre: "SOLIDARIDAD EN MARCHA",
                          Calle: "94",
                          Altura: "2560",
                          per_juridi: "SI",
                          Encargado: "MONICA CEPEDA",
                          aÑo_inicio: "2011",
                          origen_inf: "GARAGE",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "5",
                          ninos: "65",
                          adultos: "0",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "NO",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "NO",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "25",
                          Nro_volunt: "12",
                          Capacitac: "SI",
                          Hora_rotat: "SI",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "PERECEDEROS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "SI",
                          MERIENDA: "NO",
                          ALMUERZO: "NO",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6536424.56216258555650711 -4658038.94697158876806498)",
                          url_img:"http://placehold.it/700x400",
                          id: "10",
                          Nombre: "UNA SONRISA DE BARRIOS DE PIE",
                          Calle: "562",
                          Altura: "965",
                          per_juridi: "NO",
                          Encargado: "SILVANA CALIO",
                          aÑo_inicio: "2016",
                          origen_inf: "PROPIETARIOS",
                          patio: "SI",
                          temporada: "INVIERNO",
                          cant_dias: "3",
                          ninos: "",
                          adultos: "",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "INSUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "NO",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "NO",
                          Telefonia: "SI",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "NO",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "NO",
                          Condicion: "REGULAR",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "38",
                          Nro_volunt: "",
                          Capacitac: "SI",
                          Hora_rotat: "SI",
                          Ayuda_econ: "SI",
                          Origen_fon: "DONACION",
                          Tipo_alime: "PERECEDEROS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "NO",
                          DESAYUNO: "SI",
                          MERIENDA: "NO",
                          ALMUERZO: "SI",
                          CENA: "",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6537182.53656224720180035 -4657307.14134825486689806)",
                          url_img:"http://placehold.it/700x400",
                          id: "11",
                          Nombre: "PUENTE COLGANTE",
                          Calle: "576",
                          Altura: "952",
                          per_juridi: "SI",
                          Encargado: "DELIA GENTILE",
                          aÑo_inicio: "",
                          origen_inf: "COMPRA",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "7",
                          ninos: "106",
                          adultos: "70",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "SI",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "SI",
                          Nro_trabaj: "3",
                          Nro_volunt: "3",
                          Capacitac: "SI",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "MUNICIPALIDAD",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "NO",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "NO",
                          MERIENDA: "NO",
                          ALMUERZO: "SI",
                          CENA: "NO",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6535366.51194562762975693 -4658711.30987232178449631)",
                          url_img:"http://placehold.it/700x400",
                          id: "12",
                          Nombre: "ALFA Y OMEGA",
                          Calle: "546",
                          Altura: "1037",
                          per_juridi: "SI",
                          Encargado: "PASTORES DE LA IGLESIA",
                          aÑo_inicio: "",
                          origen_inf: "COMPRA",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "1",
                          ninos: "15",
                          adultos: "0",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "SI",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "6",
                          Nro_volunt: "6",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "CUENTA PROPIA",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "NO",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "NO",
                          MERIENDA: "NO",
                          ALMUERZO: "SI",
                          CENA: "NO",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6538666.67759270500391722 -4655924.77508826181292534)",
                          url_img:"http://placehold.it/700x400",
                          id: "13",
                          Nombre: "EL PAPI",
                          Calle: "76",
                          Altura: "1838",
                          per_juridi: "NO",
                          Encargado: "ELIZABETH DE GODOY",
                          aÑo_inicio: "2017",
                          origen_inf: "COMPRA",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "1",
                          ninos: "20",
                          adultos: "15",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "NO",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "NO",
                          Telefonia: "NO",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "NO",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "NO",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "2",
                          Nro_volunt: "2",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "SI",
                          Origen_fon: "Estado",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "NO",
                          Ropa_calza: "SI",
                          Otros_serv: "NO",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "NO",
                          MERIENDA: "NO",
                          ALMUERZO: "SI",
                          CENA: "NO",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  ,
                          Actualizado: "Mayo de 2019"                  
                        },
                        {
                          wkt_geom: "Point (-6536327.17575693596154451 -4656735.97995686810463667)",
                          url_img:"http://placehold.it/700x400",
                          id: "14",
                          Nombre: "CARITAS STA. MAGDALENA CANOSSA",
                          Calle: "541",
                          Altura: "",
                          per_juridi: "NO",
                          Encargado: "HERMANAS CANOSSIANAS",
                          aÑo_inicio: "1982",
                          origen_inf: "COMPRA",
                          patio: "NO",
                          temporada: "TODO EL AÑO",
                          cant_dias: "3",
                          ninos: "20",
                          adultos: "",
                          Espacio: "SUFICIENTE",
                          Almacenaje: "SUFICIENTE",
                          Mobiliario: "SUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "NO",
                          Telefonia: "NO",
                          Transporte: "NO",
                          Limpieza: "SI",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "BUENA",
                          Mantenimie: "MUCHO",
                          Nro_trabaj: "15",
                          Nro_volunt: "15",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "SI",
                          Otros_serv: "SI",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "NO",
                          MERIENDA: "SI",
                          ALMUERZO: "SI",
                          CENA: "NO",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6538450.30187788605690002 -4656152.30125168059021235)",
                          url_img:"https://scontent.faep8-1.fna.fbcdn.net/v/t1.0-9/s960x960/31902043_1654179318033097_7716096265536143360_o.jpg?_nc_cat=101&_nc_sid=dd9801&_nc_eui2=AeH3PsZ43MCZzBmk1G-eVl69LKFVCEUexwssoVUIRR7HCxhAJGRgQrjCueDf4ATFgzPGGPrd4ggrac8DKDg0_2LQ&_nc_ohc=tVFPZQ4OfkoAX_mgnWt&_nc_ht=scontent.faep8-1.fna&_nc_tp=7&oh=7c8e8ea12a5108a1ce83ddf9cfab4fa1&oe=5F385AB2",
                          id: "15",
                          Nombre: "MATE COCIDO",
                          Calle: "72",
                          Altura: "1854",
                          per_juridi: "NO",
                          Encargado: "GRACIANA CALARCO",
                          aÑo_inicio: "2000",
                          origen_inf: "COMPRA",
                          patio: "SI",
                          temporada: "TODO EL AÑO",
                          cant_dias: "5",
                          ninos: "100",
                          adultos: "0",
                          Espacio: "INSUFICIENTE",
                          Almacenaje: "INSUFICIENTE",
                          Mobiliario: "INSUFICIENTE",
                          Luz: "SI",
                          Gas: "SI",
                          Agua: "SI",
                          Cloacas: "SI",
                          Internet: "SI",
                          Telefonia: "SI",
                          Transporte: "NO",
                          Limpieza: "NO",
                          Matafuegos: "SI",
                          Puertas: "SI",
                          Vidrios: "SI",
                          Calefaccio: "SI",
                          Condicion: "REGULAR",
                          Mantenimie: "POCO",
                          Nro_trabaj: "3",
                          Nro_volunt: "8",
                          Capacitac: "NO",
                          Hora_rotat: "NO",
                          Ayuda_econ: "NO",
                          Origen_fon: "DONACION",
                          Tipo_alime: "AMBOS",
                          Plan_Nutri: "NO",
                          Apoyo_esco: "SI",
                          Ropa_calza: "SI",
                          Otros_serv: "",
                          BaÑos: "SI",
                          Ventanas: "SI",
                          DESAYUNO: "NO",
                          MERIENDA: "NO",
                          ALMUERZO: "SI",
                          CENA: "NO",
                          Estado: "ACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6534124.70630674250423908 -4659358.1156602781265974)",
                          url_img:"http://placehold.it/700x400",
                          id: "16",
                          Nombre: "LOS ANGELITOS",
                          Calle: "529",
                          Altura: "1368",
                          per_juridi: "",
                          Encargado: "",
                          aÑo_inicio: "",
                          origen_inf: "",
                          patio: "",
                          temporada: "",
                          cant_dias: "",
                          ninos: "",
                          adultos: "",
                          Espacio: "",
                          Almacenaje: "",
                          Mobiliario: "",
                          Luz: "",
                          Gas: "",
                          Agua: "",
                          Cloacas: "",
                          Internet: "",
                          Telefonia: "",
                          Transporte: "",
                          Limpieza: "",
                          Matafuegos: "",
                          Puertas: "",
                          Vidrios: "",
                          Calefaccio: "",
                          Condicion: "",
                          Mantenimie: "",
                          Nro_trabaj: "",
                          Nro_volunt: "",
                          Capacitac: "",
                          Hora_rotat: "",
                          Ayuda_econ: "",
                          Origen_fon: "",
                          Tipo_alime: "",
                          Plan_Nutri: "",
                          Apoyo_esco: "",
                          Ropa_calza: "",
                          Otros_serv: "",
                          BaÑos: "",
                          Ventanas: "",
                          DESAYUNO: "",
                          MERIENDA: "",
                          ALMUERZO: "",
                          CENA: "NO",
                          Estado: "INACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6536288.34025340992957354 -4657859.10601591970771551)",
                          url_img:"http://placehold.it/700x400",
                          id: "17",
                          Nombre: "EVANGELICO",
                          Calle: "562",
                          Altura: "1095",
                          per_juridi: "",
                          Encargado: "",
                          aÑo_inicio: "",
                          origen_inf: "",
                          patio: "",
                          temporada: "",
                          cant_dias: "",
                          ninos: "",
                          adultos: "",
                          Espacio: "",
                          Almacenaje: "",
                          Mobiliario: "",
                          Luz: "",
                          Gas: "",
                          Agua: "",
                          Cloacas: "",
                          Internet: "",
                          Telefonia: "",
                          Transporte: "",
                          Limpieza: "",
                          Matafuegos: "",
                          Puertas: "",
                          Vidrios: "",
                          Calefaccio: "",
                          Condicion: "",
                          Mantenimie: "",
                          Nro_trabaj: "",
                          Nro_volunt: "",
                          Capacitac: "",
                          Hora_rotat: "",
                          Ayuda_econ: "",
                          Origen_fon: "",
                          Tipo_alime: "",
                          Plan_Nutri: "",
                          Apoyo_esco: "",
                          Ropa_calza: "",
                          Otros_serv: "",
                          BaÑos: "",
                          Ventanas: "",
                          DESAYUNO: "",
                          MERIENDA: "",
                          ALMUERZO: "",
                          CENA: "",
                          Estado: "INACTIVO",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6535824.28304824698716402 -4657242.65714380610734224)",
                          url_img:"http://placehold.it/700x400",
                          id: "18",
                          Nombre: "TORTUGUITAS",
                          Calle: "564",
                          Altura: "1873",
                          per_juridi: "",
                          Encargado: "",
                          aÑo_inicio: "",
                          origen_inf: "",
                          patio: "",
                          temporada: "",
                          cant_dias: "",
                          ninos: "",
                          adultos: "",
                          Espacio: "",
                          Almacenaje: "",
                          Mobiliario: "",
                          Luz: "",
                          Gas: "",
                          Agua: "",
                          Cloacas: "",
                          Internet: "",
                          Telefonia: "",
                          Transporte: "",
                          Limpieza: "",
                          Matafuegos: "",
                          Puertas: "",
                          Vidrios: "",
                          Calefaccio: "",
                          Condicion: "",
                          Mantenimie: "",
                          Nro_trabaj: "",
                          Nro_volunt: "",
                          Capacitac: "",
                          Hora_rotat: "",
                          Ayuda_econ: "",
                          Origen_fon: "",
                          Tipo_alime: "",
                          Plan_Nutri: "",
                          Apoyo_esco: "",
                          Ropa_calza: "",
                          Otros_serv: "",
                          BaÑos: "",
                          Ventanas: "",
                          DESAYUNO: "",
                          MERIENDA: "",
                          ALMUERZO: "",
                          CENA: "",
                          Estado: "FALTA ENCUESTA",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6538997.6346849612891674 -4656040.72931899875402451)",
                          url_img:"http://placehold.it/700x400",
                          id: "19",
                          Nombre: "GRANITO DE ARENA",
                          Calle: "78",
                          Altura: "",
                          per_juridi: "",
                          Encargado: "",
                          aÑo_inicio: "",
                          origen_inf: "",
                          patio: "",
                          temporada: "",
                          cant_dias: "",
                          ninos: "",
                          adultos: "",
                          Espacio: "",
                          Almacenaje: "",
                          Mobiliario: "",
                          Luz: "",
                          Gas: "",
                          Agua: "",
                          Cloacas: "",
                          Internet: "",
                          Telefonia: "",
                          Transporte: "",
                          Limpieza: "",
                          Matafuegos: "",
                          Puertas: "",
                          Vidrios: "",
                          Calefaccio: "",
                          Condicion: "",
                          Mantenimie: "",
                          Nro_trabaj: "",
                          Nro_volunt: "",
                          Capacitac: "",
                          Hora_rotat: "",
                          Ayuda_econ: "",
                          Origen_fon: "",
                          Tipo_alime: "",
                          Plan_Nutri: "",
                          Apoyo_esco: "",
                          Ropa_calza: "",
                          Otros_serv: "",
                          BaÑos: "",
                          Ventanas: "",
                          DESAYUNO: "",
                          MERIENDA: "",
                          ALMUERZO: "",
                          CENA: "",
                          Estado: "FALTA ENCUESTA",
                          Actualizado: "Mayo de 2019"  
                        },
                        {
                          wkt_geom: "Point (-6539869.70828872919082642 -4659178.03131406754255295)",
                          url_img:"http://placehold.it/700x400",
                          id: "20",
                          Nombre: "NUESTRA SRA. NUEVA POMPEYA",
                          Calle: "79",
                          Altura: "",
                          per_juridi: "",
                          Encargado: "",
                          aÑo_inicio: "",
                          origen_inf: "",
                          patio: "",
                          temporada: "",
                          cant_dias: "",
                          ninos: "",
                          adultos: "",
                          Espacio: "",
                          Almacenaje: "",
                          Mobiliario: "",
                          Luz: "",
                          Gas: "",
                          Agua: "",
                          Cloacas: "",
                          Internet: "",
                          Telefonia: "",
                          Transporte: "",
                          Limpieza: "",
                          Matafuegos: "",
                          Puertas: "",
                          Vidrios: "",
                          Calefaccio: "",
                          Condicion: "",
                          Mantenimie: "",
                          Nro_trabaj: "",
                          Nro_volunt: "",
                          Capacitac: "",
                          Hora_rotat: "",
                          Ayuda_econ: "",
                          Origen_fon: "",
                          Tipo_alime: "",
                          Plan_Nutri: "",
                          Apoyo_esco: "",
                          Ropa_calza: "",
                          Otros_serv: "",
                          BaÑos: "",
                          Ventanas: "",
                          DESAYUNO: "",
                          MERIENDA: "",
                          ALMUERZO: "",
                          CENA: "",
                          Estado: "FALTA ENCUESTA",
                          Actualizado: "Mayo de 2019"  
                        },
         
	
                      ];
                      
                    });